### ISSUE TITLE
Please upgrade your package version after breaking changes

### ISSUE THREAD

**Issue by mwaibel-go** [lukeed/hexoid#3]
Commit cdbae71503c33b20315290dcd543ed4702fb1366  (break: use `hexoid` named export) [broke formidable@2.0.1](https://github.com/node-formidable/formidable/issues/871). You should increase your package’s major version number after breaking changes  in order to not affect packages that depend on you.

Consider, for instance, https://semver.org/ for more information.

Thank you for your time.

Edit:

Also remember to release the new version as an npm package.

**Comment by lukeed** [comment]
It’s not published
