### ISSUE TITLE
`exports` should be present in published `package.json` on npm

### ISSUE THREAD

**Issue by antoinepairet** [lukeed/hexoid#5]
Reference: https://github.com/web-infra-dev/rspack/issues/3240

TL;DR;
`hexoid` cannot be bundled by Rspack and Webpack when the target is `node` because `exports` field of `package.json` is not published on NPM.

- https://www.npmjs.com/package/hexoid?activeTab=code does not have `exports` field in package.json
- while https://github.com/lukeed/hexoid/blob/master/package.json#L6 has it

**Comment by lukeed** [comment]
hexoid@2.0.0 is now available
